import { Ministry, Employee, BudgetItem, InventoryItem, FixedAsset, ProcurementRequest, TrainingCourse, JobApplication, CashAdvance, BankAccount, LeaveRequest, Shift, MaterialRequest, Account, JournalEntry, Invoice } from './types';

export const MINISTRIES: Ministry[] = [
  { id: 'mof', nameEn: 'Ministry of Finance', nameAr: 'وزارة المالية', logo: 'https://picsum.photos/id/1/200/200' },
  { id: 'moi', nameEn: 'Ministry of Interior', nameAr: 'وزارة الداخلية', logo: 'https://picsum.photos/id/2/200/200' },
  { id: 'moe', nameEn: 'Ministry of Education', nameAr: 'وزارة التربية', logo: 'https://picsum.photos/id/3/200/200' },
  { id: 'moh', nameEn: 'Ministry of Health', nameAr: 'وزارة الصحة', logo: 'https://picsum.photos/id/4/200/200' },
];

export const EMPLOYEES: Employee[] = [
  { id: 'E001', code: '23574210', company: 'Taqadum Iraq Co.', fullNameEn: 'Ahmed Al-Baghdadi', fullNameAr: 'أحمد البغدادي', position: 'Senior Accountant', department: 'Finance', status: 'Active', salary: 1500000, joinDate: '2019-03-12', leaveBalance: 21, jobType: 'Full Time' },
  { id: 'E002', code: '23574211', company: 'Taqadum Iraq Co.', fullNameEn: 'Fatima Hassan', fullNameAr: 'فاطمة حسن', position: 'HR Specialist', department: 'Human Resources', status: 'Active', salary: 1200000, joinDate: '2020-06-01', leaveBalance: 14, jobType: 'Full Time' },
  { id: 'E003', code: '23574212', company: 'Taqadum Iraq Co.', fullNameEn: 'Ali Hussein', fullNameAr: 'علي حسين', position: 'Warehouse Manager', department: 'SCM', status: 'On Leave', salary: 1350000, joinDate: '2018-11-20', leaveBalance: 5, jobType: 'Shift' },
  { id: 'E004', code: '23574213', company: 'Taqadum Iraq Co.', fullNameEn: 'Zainab Mohammed', fullNameAr: 'زينب محمد', position: 'IT Support', department: 'IT', status: 'Active', salary: 1100000, joinDate: '2021-01-15', leaveBalance: 18, jobType: 'Full Time' },
  { id: 'E005', code: '23574214', company: 'Taqadum Iraq Co.', fullNameEn: 'Omar Farouk', fullNameAr: 'عمر فاروق', position: 'Procurement Officer', department: 'SCM', status: 'Active', salary: 1250000, joinDate: '2022-04-10', leaveBalance: 25, jobType: 'Full Time' },
];

export const SHIFTS: Shift[] = [
  { id: 'S01', nameEn: 'Employee Shift', nameAr: 'مناوبة موظف', startTime: '08:00 AM', endTime: '04:00 PM' },
  { id: 'S02', nameEn: 'Accountant Shift', nameAr: 'مناوبة محاسب', startTime: '09:00 AM', endTime: '05:00 PM' },
];

export const BUDGET_ITEMS: BudgetItem[] = [
  { id: 'B001', sectionType: 'I', code: '101', itemEn: 'Basic Salaries', itemAr: 'الرواتب الأساسية', allocation: 500000000, spent: 420000000 },
  { id: 'B002', sectionType: 'I', code: '102', itemEn: 'Allowances & Benefits', itemAr: 'المخصصات والمزايا', allocation: 150000000, spent: 130000000 },
  { id: 'B003', sectionType: 'II', code: '201', itemEn: 'Office Supplies', itemAr: 'القرطاسية والتجهيزات', allocation: 25000000, spent: 12000000 },
  { id: 'B004', sectionType: 'II', code: '205', itemEn: 'Maintenance', itemAr: 'الصيانة', allocation: 50000000, spent: 45000000 },
  { id: 'B005', sectionType: 'II', code: '210', itemEn: 'Capital Projects', itemAr: 'المشاريع الرأسمالية', allocation: 1200000000, spent: 300000000 },
];

export const INVENTORY: InventoryItem[] = [
  { id: 'I001', nameEn: 'Desktop Computer Dell', nameAr: 'حاسوب مكتبي ديل', sku: 'IT-COMP-001', warehouse: 'Main Baghdad WH', quantity: 45, unit: 'Pcs', status: 'In Stock', group: 'IT Equipment', brand: 'Dell' },
  { id: 'I002', nameEn: 'Office Chair Ergonomic', nameAr: 'كرسي مكتب طبي', sku: 'FUR-CHR-022', warehouse: 'Basra Branch', quantity: 12, unit: 'Pcs', status: 'Low Stock', group: 'Furniture', brand: 'Ikea' },
  { id: 'I003', nameEn: 'A4 Paper Ream', nameAr: 'ورق A4', sku: 'SUP-PAP-100', warehouse: 'Main Baghdad WH', quantity: 500, unit: 'Box', status: 'In Stock', group: 'Consumables', brand: 'Double A' },
  { id: 'I004', nameEn: 'Printer Ink HP 85A', nameAr: 'حبر طابعة HP 85A', sku: 'IT-INK-085', warehouse: 'Mosul Branch', quantity: 0, unit: 'Cartridge', status: 'Out of Stock', group: 'Consumables', brand: 'HP' },
];

export const MATERIAL_REQUESTS: MaterialRequest[] = [
    { id: 'MR-2023-001', date: '2023-10-01', user: 'Ahmed Al-Baghdadi', purpose: 'Purchase', requiredDate: '2023-10-10', status: 'Pending', items: [{itemCode: 'IT-COMP-001', qty: 5, warehouse: 'Main WH'}] },
    { id: 'MR-2023-002', date: '2023-10-05', user: 'Ali Hussein', purpose: 'Material Transfer', requiredDate: '2023-10-06', status: 'Draft', items: [{itemCode: 'SUP-PAP-100', qty: 50, warehouse: 'Basra Branch'}] },
];

export const ASSETS: FixedAsset[] = [
  { id: 'A001', nameEn: 'Toyota Land Cruiser', nameAr: 'تويوتا لاند كروزر', purchaseDate: '2022-01-10', value: 85000000, bookValue: 65000000, depreciationMethod: 'Actual Days', location: 'HQ Garage' },
  { id: 'A002', nameEn: 'Power Generator 500kVA', nameAr: 'مولدة كهرباء 500 ك.ف', purchaseDate: '2021-05-20', value: 35000000, bookValue: 21000000, depreciationMethod: 'Fixed Monthly', location: 'Warehouse B' },
];

export const PROCUREMENT_REQUESTS: ProcurementRequest[] = [
  { id: 'PR001', description: '50x Laptops for IT Dept', requester: 'IT Department', amount: 45000000, status: 'Payment', date: '2023-10-01' },
  { id: 'PR002', description: 'Office Furniture Renovation', requester: 'Admin', amount: 12000000, status: 'Receiving', date: '2023-10-15' },
  { id: 'PR003', description: 'Annual Stationery Supply', requester: 'Warehouse', amount: 5000000, status: 'Pricing', date: '2023-10-20' },
  { id: 'PR004', description: 'Cleaning Services Contract', requester: 'Services', amount: 8000000, status: 'Request', date: '2023-10-25' },
];

export const TRAINING_COURSES: TrainingCourse[] = [
  { id: 'TR01', titleEn: 'Advanced Accounting Standards', titleAr: 'المعايير المحاسبية المتقدمة', provider: 'Baghdad University', startDate: '2023-11-10', attendees: 15, status: 'Scheduled' },
  { id: 'TR02', titleEn: 'IT Security Fundamentals', titleAr: 'أساسيات أمن المعلومات', provider: 'Internal IT', startDate: '2023-10-20', attendees: 25, status: 'In Progress' },
];

export const JOB_APPLICATIONS: JobApplication[] = [
  { id: 'JA01', candidateName: 'Hassan Ali', position: 'Senior Accountant', stage: 'Interview', date: '2023-10-22' },
  { id: 'JA02', candidateName: 'Noor Jassim', position: 'HR Assistant', stage: 'Applied', date: '2023-10-24' },
  { id: 'JA03', candidateName: 'Mustafa Kareem', position: 'Driver', stage: 'Hired', date: '2023-10-01' },
];

export const CASH_ADVANCES: CashAdvance[] = [
  { id: 'CA01', type: 'Permanent', recipient: 'Finance Dept Head', amount: 5000000, descriptionEn: 'Petty Cash Fund', descriptionAr: 'سلفة نثرية دائمة', status: 'Approved' },
  { id: 'CA02', type: 'Temporary', recipient: 'Ahmed Al-Baghdadi', amount: 250000, descriptionEn: 'Transport for Site Visit', descriptionAr: 'نقل زيارة موقعية', status: 'Liquidated' },
  { id: 'CA03', type: 'Temporary', recipient: 'Ali Hussein', amount: 1500000, descriptionEn: 'Emergency Repairs', descriptionAr: 'صيانة طارئة', status: 'Pending' },
];

export const BANKS: BankAccount[] = [
  { id: 'BNK01', bankName: 'Rafidain Bank', accountNumber: 'IQ-RAF-001234', balance: 4500000000, currency: 'IQD', lastReconciled: '2023-09-30' },
  { id: 'BNK02', bankName: 'Trade Bank of Iraq (TBI)', accountNumber: 'IQ-TBI-998877', balance: 1200000, currency: 'USD', lastReconciled: '2023-10-01' },
];

export const MY_LEAVES: LeaveRequest[] = [
  { id: 'L01', type: 'Vacation', startDate: '2023-11-15', days: 5, status: 'Pending' },
  { id: 'L02', type: 'Sick', startDate: '2023-08-10', days: 2, status: 'Approved' },
];

export const ACCOUNTS: Account[] = [
  { id: '1', code: '1000', nameEn: 'Assets', nameAr: 'الموجودات', type: 'Asset', isGroup: true, balance: 125000000, children: [
    { id: '11', code: '1100', nameEn: 'Fixed Assets', nameAr: 'موجودات ثابتة', type: 'Asset', isGroup: true, balance: 85000000 },
    { id: '12', code: '1200', nameEn: 'Current Assets', nameAr: 'موجودات المتغيرة', type: 'Asset', isGroup: true, balance: 40000000 }
  ]},
  { id: '2', code: '2000', nameEn: 'Liabilities', nameAr: 'المطلوبات', type: 'Liability', isGroup: true, balance: 35000000, children: [
    { id: '21', code: '2100', nameEn: 'Current Liabilities', nameAr: 'المطلوبات الثابتة', type: 'Liability', isGroup: true, balance: 35000000 }
  ]},
  { id: '3', code: '3000', nameEn: 'Equity', nameAr: 'صافي الربح التجاري', type: 'Equity', isGroup: true, balance: 90000000 },
  { id: '4', code: '4000', nameEn: 'Expenses', nameAr: 'المصاريف', type: 'Expense', isGroup: true, balance: 2500000 },
  { id: '5', code: '5000', nameEn: 'Income', nameAr: 'الحسوميات', type: 'Income', isGroup: true, balance: 15000000 },
];

export const JOURNAL_ENTRIES: JournalEntry[] = [
  { id: 'JE-001', date: '2023-10-25', reference: 'INV-2023-001', description: 'Opening Balance', totalDebit: 1500000, totalCredit: 1500000, status: 'Posted' },
  { id: 'JE-002', date: '2023-10-26', reference: 'PAY-2023-005', description: 'Payment to Supplier', totalDebit: 500000, totalCredit: 500000, status: 'Draft' },
];

export const INVOICES: Invoice[] = [
  { id: 'INV-001', type: 'Sales', partyName: 'Baghdad Retailers', date: '2023-10-20', dueDate: '2023-11-20', total: 2500000, status: 'Unpaid' },
  { id: 'PINV-001', type: 'Purchase', partyName: 'Tech Suppliers Ltd', date: '2023-10-15', dueDate: '2023-10-30', total: 4500000, status: 'Paid' },
];

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome to',
    selectMinistry: 'Select Ministry',
    login: 'Login',
    username: 'Username',
    password: 'Password',
    dashboard: 'Dashboard',
    hr: 'Human Resources',
    finance: 'Accounting',
    scm: 'Warehouse & SCM',
    ess: 'Self Service',
    settings: 'Settings',
    logout: 'Logout',
    employees: 'Employees',
    payroll: 'Payroll',
    attendance: 'Attendance',
    training: 'Training',
    recruitment: 'Recruitment',
    budget: 'Budget',
    banking: 'Banking',
    cashAdvances: 'Cash Advances',
    generalLedger: 'General Ledger',
    inventory: 'Inventory',
    procurement: 'Procurement',
    fixedAssets: 'Fixed Assets',
    totalEmployees: 'Total Employees',
    budgetUtilization: 'Budget Utilization',
    lowStockItems: 'Low Stock Items',
    search: 'Search...',
    actions: 'Actions',
    status: 'Status',
    ministryOf: 'Ministry of',
    iraqDataCenter: 'Iraq National Data Center',
    demoHint: 'Use demo/demo to login',
    copyright: '© 2024 Iraqi National Data Center. All rights reserved.',
    requestLeave: 'Request Leave',
    requestLoan: 'Request Loan',
    payslip: 'Payslip',
    sectionI: 'Section I: Salaries',
    sectionII: 'Section II: Operational',
    // HR Specific
    employee: 'Employee',
    leaveRequest: 'Leave Request',
    monthlyAttendance: 'Monthly Attendance List',
    jobApplicant: 'Job Applicant',
    infoDashboard: 'Info Dashboard',
    vacations: 'Vacations',
    shiftManagement: 'Shift Management',
    employeeProcedures: 'Employee Procedures',
    theEmployee: 'The Employee',
    newEmployee: 'New Employee',
    promotion: 'Promotion',
    healthInsurance: 'Health Insurance',
    shiftType: 'Shift Type',
    startTime: 'Start Time',
    endTime: 'End Time',
    save: 'Save',
    cancel: 'Cancel',
    code: 'Code',
    company: 'Company',
    firstName: 'First Name',
    middleName: 'Middle Name',
    lastName: 'Last Name',
    dob: 'Date of Birth',
    joinDate: 'Join Date',
    jobType: 'Job Type',
    // SCM Specific
    items: 'Items',
    materialRequest: 'Material Request',
    stockEntry: 'Stock Entry',
    purchaseReceipt: 'Purchase Receipt',
    stockLedger: 'Stock Ledger',
    scmSettings: 'Settings',
    stockReports: 'Stock Reports',
    stockEntries: 'Stock Entries',
    commodities: 'Commodities & Pricing',
    newItem: 'New Item',
    itemGroup: 'Item Group',
    brand: 'Brand',
    maintainStock: 'Maintain Stock',
    warehouse: 'Warehouse',
    uom: 'UOM',
    add: 'Add',
    purpose: 'Purpose',
    requiredDate: 'Required Date',
    quantity: 'Quantity',
    user: 'User',
    date: 'Date',
    purchaseAnalytics: 'Purchase Analytics',
    newWarehouse: 'New Warehouse',
    newWarehouseTitle: 'Create New Warehouse',
    parentCompany: 'Parent Company',
    isGroup: 'Is Group',
    entryType: 'Entry Type',
    sourceWarehouse: 'Source Warehouse',
    targetWarehouse: 'Target Warehouse',
    // Finance Specific
    accounting: 'Accounting',
    journalEntry: 'Journal Entry',
    purchaseInvoice: 'Purchase Invoice',
    salesInvoice: 'Sales Invoice',
    chartOfAccounts: 'Chart of Accounts',
    accountsPayable: 'Accounts Payable',
    accountsReceivable: 'Accounts Receivable and Receivables',
    mainAccounts: 'Main Accounts',
    financialStatements: 'Financial Statements',
    multiCurrency: 'Multi-Currency',
    profitability: 'Profitability',
    taxes: 'Taxes',
    trialBalance: 'Trial Balance',
    balanceSheet: 'Balance Sheet',
    profitLoss: 'Profit and Loss',
    cashFlow: 'Cash Flow',
    costCenter: 'Cost Center',
    openingBalance: 'Opening Balance',
    debit: 'Debit',
    credit: 'Credit',
    closingBalance: 'Closing Balance',
    ledger: 'Ledger',
    account: 'Account',
    party: 'Party',
    totalDebit: 'Total Debit',
    totalCredit: 'Total Credit',
    difference: 'Difference',
    customer: 'Customer',
    supplier: 'Supplier',
    invoiceDate: 'Invoice Date',
    dueDate: 'Due Date',
    paymentTerms: 'Payment Terms',
    currency: 'Currency',
    exchangeRate: 'Exchange Rate',
    amount: 'Amount',
    itemCode: 'Item Code',
    rate: 'Rate',
    addLine: 'Add Line',
    postingDate: 'Posting Date',
    referenceNumber: 'Reference Number',
    dimensions: 'Dimensions',
    remarks: 'Remarks',
    fiscalYear: 'Fiscal Year',
    financeBook: 'Finance Book',
  },
  ar: {
    welcome: 'مرحبا بكم في',
    selectMinistry: 'اختر الوزارة',
    login: 'تسجيل الدخول',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    dashboard: 'لوحة المعلومات',
    hr: 'الموارد البشرية',
    finance: 'المحاسبة',
    scm: 'المخازن والمشتريات',
    ess: 'الخدمة الذاتية',
    settings: 'الإعدادات',
    logout: 'خروج',
    employees: 'الموظفين',
    payroll: 'الرواتب',
    attendance: 'الحضور والانصراف',
    training: 'التدريب',
    recruitment: 'التعيينات',
    budget: 'الموازنة',
    banking: 'المصارف',
    cashAdvances: 'السلف',
    generalLedger: 'دفتـر الأستاذ',
    inventory: 'المخزون',
    procurement: 'المشتريات',
    fixedAssets: 'الأصول الثابتة',
    totalEmployees: 'إجمالي الموظفين',
    budgetUtilization: 'استخدام الموازنة',
    lowStockItems: 'مواد منخفضة الرصيد',
    search: 'بحث...',
    actions: 'إجراءات',
    status: 'الحالة',
    ministryOf: 'وزارة',
    iraqDataCenter: 'مركز البيانات الوطني العراقي',
    demoHint: 'استخدم demo/demo للدخول',
    copyright: '© 2024 مركز البيانات الوطني العراقي. جميع الحقوق محفوظة.',
    requestLeave: 'طلب إجازة',
    requestLoan: 'طلب سلفة',
    payslip: 'قسيمة الراتب',
    sectionI: 'الفصل الأول: الرواتب',
    sectionII: 'الفصل الثاني: التشغيلية',
    // HR Specific
    employee: 'الموظف',
    leaveRequest: 'طلب إجازة',
    monthlyAttendance: 'قائمة الحضور الشهرية',
    jobApplicant: 'طالب الوظيفة',
    infoDashboard: 'لوحة المعلومات',
    vacations: 'الاجازات',
    shiftManagement: 'إدارة المناوبة',
    employeeProcedures: 'إجراءات الموظفين',
    theEmployee: 'الموظف',
    newEmployee: 'موظف جديد',
    promotion: 'ترقية موظف',
    healthInsurance: 'التأمين الصحي للموظف',
    shiftType: 'نوع المناوبة',
    startTime: 'وقت البداية',
    endTime: 'وقت الانتهاء',
    save: 'حفظ',
    cancel: 'إلغاء',
    code: 'رمز الموظف',
    company: 'اسم الشركة',
    firstName: 'الاسم الأول',
    middleName: 'الاسم الأوسط',
    lastName: 'اسم العائلة',
    dob: 'تاريخ الميلاد',
    joinDate: 'تاريخ الالتحاق بالعمل',
    jobType: 'نوع الوظيفة',
    // SCM Specific
    items: 'العناصر',
    materialRequest: 'طلب مواد',
    stockEntry: 'قيد مخزون',
    purchaseReceipt: 'إستلام مشتريات',
    stockLedger: 'سجل المخزن',
    scmSettings: 'إعدادات',
    stockReports: 'تقارير الأسهم',
    stockEntries: 'قيود المخزون',
    commodities: 'السلع والتسعيرات',
    newItem: 'عنصر جديد',
    itemGroup: 'مجموعة الصنف',
    brand: 'الماركة',
    maintainStock: 'خزن المنتج',
    warehouse: 'المخزن',
    uom: 'وحدة القياس',
    add: 'إضافة',
    purpose: 'غرض الطلب',
    requiredDate: 'المطلوبة من قبل',
    quantity: 'كمية',
    user: 'المستخدم',
    date: 'التاريخ',
    purchaseAnalytics: 'تحليلات المشتريات',
    newWarehouse: 'انشاء قيد مخزون', 
    newWarehouseTitle: 'انشاء مخزن جديد',
    parentCompany: 'اسم الشركة',
    isGroup: 'Is Group', 
    entryType: 'نوع ادخال الأسهم',
    sourceWarehouse: 'المخزن المستهدف', 
    targetWarehouse: 'المخزن المستهدف', 
    // Finance Specific
    accounting: 'المحاسبة',
    journalEntry: 'القيود اليومية',
    purchaseInvoice: 'فاتورة مشتريات',
    salesInvoice: 'فاتورة مبيعات',
    chartOfAccounts: 'الشجرة المحاسبية',
    accountsPayable: 'الحسابات الدائنة',
    accountsReceivable: 'المقبوضات والحسابات المدينة',
    mainAccounts: 'الحسابات الرئيسية',
    financialStatements: 'البيانات المالية',
    multiCurrency: 'متعدد العملات',
    profitability: 'الربحية',
    taxes: 'الضرائب',
    trialBalance: 'ميزان المراجعة',
    balanceSheet: 'المركز المالي',
    profitLoss: 'الأرباح والخسائر',
    cashFlow: 'التدفق النقدي',
    costCenter: 'مركز التكلفة',
    openingBalance: 'الرصيد الافتتاحي',
    debit: 'مدين',
    credit: 'دائن',
    closingBalance: 'الرصيد الختامي',
    ledger: 'دفتر الاستاذ',
    account: 'الحساب',
    party: 'الطرف المعني',
    totalDebit: 'مجموع المدين',
    totalCredit: 'مجموع الدائن',
    difference: 'الفرق',
    customer: 'العميل',
    supplier: 'المورد',
    invoiceDate: 'تاريخ الفاتورة',
    dueDate: 'تاريخ الاستحقاق',
    paymentTerms: 'شروط الدفع',
    currency: 'العملة',
    exchangeRate: 'سعر الصرف',
    amount: 'المبلغ',
    itemCode: 'رمز الصنف',
    rate: 'السعر',
    addLine: 'إضافة سطر',
    postingDate: 'تاريخ الترحيل',
    referenceNumber: 'رقم المرجع',
    dimensions: 'الأبعاد',
    remarks: 'ملاحظات',
    fiscalYear: 'السنة المالية',
    financeBook: 'كتاب المالية',
  }
};